[listen]
bind = "localhost"

[local]
skew = 1000000000000

[local.db]
#propsd = true
#path = "http://localhost:9100/v1/conqueso"
propsd = false
path = "data/keys.json"

[log]
json = false
level = "DEBUG"
requests = true

[service]
port = 7085
